version: '3.7'
services:
  whale-shark:
    platform: linux/amd64
    build:
      context: .
      args:
        - DISCORD_TOKEN=${DISCORD_TOKEN}
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - AWS_REGION=${AWS_REGION}
      dockerfile: ./Dockerfile
    volumes:
      - ./mnt/whale-shark/discord-bot:/opt/whale-shark/discord-bot
    restart: "always"
